<?php include "includes/header.php"; ?>
    <!-- Navigation -->
 
<?php include "includes/nav.php"; ?>

<?php  
	if(isset($_GET['category'])){
		$category = clean($_GET['category']);

//seperate query for selecting the category title so we can dynamically change the heading title on the fly and match it to the category the user is viewing
	  $catQuery= "SELECT cat_title FROM categories WHERE cat_id = ?";  
	  $titleStmt = mysqli_stmt_init($connection);
	  mysqli_stmt_prepare($titleStmt, $catQuery);
	  mysqli_stmt_bind_param($titleStmt, 'i', $category);
	  mysqli_stmt_execute($titleStmt);
	  mysqli_stmt_bind_result($titleStmt, $cat_title);
	  mysqli_stmt_store_result($titleStmt);
	  mysqli_stmt_fetch($titleStmt);
	  mysqli_stmt_close($titleStmt);
}
// END category title query
            

//================================RELEVANT POSTS BY CATEGORY QUERY===================================== The information we want to display depends on a few things. One, what the current user's role is and two, what the status of the post is (published or draft). Should the user be a subscriber or a guest, they only see published posts. Admin's, however, may view drafted posts as previews. We create two seperate prepared statements. Once one of them conditionally executes, we check which one ran, get the results we queried with bind_result, and store it in variable $stmt. $stmt is the end result of this bulky query. From there we run mysqli_stmt_fetch on the $stmt(our result) and loop through the resulting array of posts with a while loop. The variables echoed in the HTML markup are generated by the mysqli_stmt_bind_result function. 
    $stmt = mysqli_stmt_init($connection);
    if(!$stmt){
        echo "error connecting";
    }
    
    if(is_admin($_SESSION['username'])){
         $query1 = "SELECT post_id, post_title, post_author, cast(post_date as date), post_update, post_image, post_content FROM posts WHERE post_category_id = ?";
         $stmt1 = mysqli_prepare($connection,$query1);
         queryConnect($stmt1);
    
     }else{
        $query2 = "SELECT post_id, post_title, post_author, cast(post_date as date), post_update, post_image, post_content FROM posts WHERE post_category_id = ? AND post_status = ?";
        $stmt2 = mysqli_prepare($connection,$query2);
        $published = 'published';
        queryConnect($stmt2);
    }

   
//Do NOT close off stmt in this if/else block. We still have to run mysqli_stmt_fetch($stmt) below
    if(isset($stmt1)){
        mysqli_stmt_bind_param($stmt1, 'i', $category);
        mysqli_stmt_execute($stmt1);
        mysqli_stmt_bind_result($stmt1, $post_id, $post_title, $post_author, $post_date, $post_update, $post_image, $post_content);
        $stmt = $stmt1;
        mysqli_stmt_store_result($stmt);

    }elseif(isset($stmt2)){
        mysqli_stmt_bind_param($stmt2, 'is', $category, $published);
        mysqli_stmt_execute($stmt2);
        mysqli_stmt_bind_result($stmt2, $post_id, $post_title, $post_author, $post_date, $post_update, $post_image, $post_content);
        $stmt = $stmt2;
        mysqli_stmt_store_result($stmt);
    }else{
        exit("No query executed. Both $stmt1 and $stmt2 failed to run");
    }
?>




<div class="post-category offset">
	<div class="jumbotron">
		<h1 class="heading--secondary"> <?php echo "$cat_title" ?> </h1>
		  <div class="heading-underline"></div>
			<div class="container-fluid content-row">
	  			<div class="row narrow justify-content-md-center">
					<?php 
						while(mysqli_stmt_fetch($stmt)): 
					?>
					 	
		<div class="col-6 col-sm-6 col-md-6 col-lg-3">
			<div class="os-animation" data-animation="zoomInUp">
				<div class="card-container">
					<div class="card text-center" >
						<!-- <div class="card--img-wrapper bg-light">
						  <a href="post.php?p_id=<?php echo $post_id?>">
							<img class="card-img-top img-responsive img-fluid" src="images/<?php echo $post_image;?>" alt="featured post image" width="400" height="400">
						  </a>
		            	</div> -->
						<div class="card--body" style="background-image: linear-gradient(rgba(20,20,20,.5),rgba(20,20,20,.5)),url(../images/<?php echo $post_image;?>);">
								<div class="container-fluid">
										<h4 class="card--title text-center"><a class="blog-meta-data" href="../articles/<?php echo $post_id;?>"><?php echo $post_title; ?></a>
										</h4>
								</div>


								<div class="container">
									<p class="blog-meta-data card--text card-excerpt"><?php echo substr(file_get_contents($post_content, FILE_USE_INCLUDE_PATH),0,150)."...";?></p>
									<h5 class="card--date">Published On <?php echo $post_date;?> </h5>
								</div> 
								 
								<div class="card-clickable">
								  <a class="btn btn-sm btn-turquoise btn-turquoise--articles" href="../articles/<?php echo $post_id;?>">View <span class="glyphicon glyphicon-chevron-right"></span></a>
								</div>
						</div>
						<div class="card--footer">
	     					<small class="text-muted"><!-- <?php date_default_timezone_set('America/Los_Angeles')?> -->Last updated <?php echo TimeAgo($post_update, date("Y-m-d H:i:s")); ?></small>
	    				</div>
					</div>
				</div>
		</div>
	</div>
					<?php
					 endwhile;
				  	mysqli_stmt_close($stmt);
				    //closes off the else consition and while loop querying all post information. The HTML code is now automatically replecated for each new post by being encased in this loop. 
					?>
				</div> <!--END .row -->
			</div> <!--END .container-fluid -->
				
	</div>
</div>
<?php include "includes/footer.php"; ?>
