<?php include "includes/header.php"; ?>
    <!-- Navigation -->
   
<?php include "includes/navigation.php"; ?>
    <!-- Page Content -->
    <?php 
    //fetch the category URL parameter we pass
if(isset($_GET['category'])){
    $category = clean($_GET['category']);
            
                
                //The information we want to display depends on a few things. One, what the current user's role is and two, what the status of the post is (published or draft). Should the user be a subscriber or a guest, they only see published posts. Admin's, however, may view drafted posts as previews. We create two seperate prepared statements. Once one of them conditionally executes, we check which one ran, get the results we queried with bind_result, and store it in variable $stmt. $stmt is the end result of this bulky query. From there we run mysqli_stmt_fetch on the $stmt(our result) and loop through the resulting array of posts with a while loop. The variables echoed in the HTML markup are generated by the mysqli_stmt_bind_result function. 
    $stmt = mysqli_stmt_init($connection);
    if(!$stmt){
        echo "error connecting";
    }
    
    if(is_admin($_SESSION['username'])){
         $query1 = "SELECT post_id, post_title, post_author, post_date, post_image, post_content FROM posts WHERE post_category_id = ?";
         $stmt1 = mysqli_prepare($connection,$query1);
         queryConnect($stmt1);
    
     }else{
        $query2 = "SELECT post_id, post_title, post_author, post_date, post_image, post_content FROM posts WHERE post_category_id = ? AND post_status = ?";
        $stmt2 = mysqli_prepare($connection,$query2);
        $published = 'published';
        queryConnect($stmt2);
    }

   
//Do NOT close off the stmts in this if/else block. We still have to run mysqli_stmt_fetch($stmt) below
    if(isset($stmt1)){
        mysqli_stmt_bind_param($stmt1, 'i', $category);
        mysqli_stmt_execute($stmt1);
        mysqli_stmt_bind_result($stmt1, $post_id, $post_title, $post_author, $post_date, $post_image, $post_content);
        $stmt = $stmt1;
        mysqli_stmt_store_result($stmt);

    }elseif(isset($stmt2)){
        mysqli_stmt_bind_param($stmt2, 'is', $category, $published);
        mysqli_stmt_execute($stmt2);
        mysqli_stmt_bind_result($stmt2, $post_id, $post_title, $post_author, $post_date, $post_image, $post_content);
        $stmt = $stmt2;
        mysqli_stmt_store_result($stmt);
    }else{
        exit("No query executed. Both $stmt1 and $stmt2 failed to run");
    }


//seperate query for selecting the category title so we can dynamically change the heading title on the fly and match it to the category the user is viewing
  $catQuery= "SELECT cat_title FROM categories WHERE cat_id = ?";  
  $titleStmt = mysqli_stmt_init($connection);
  mysqli_stmt_prepare($titleStmt, $catQuery);
  mysqli_stmt_bind_param($titleStmt, 'i', $category);
  mysqli_stmt_execute($titleStmt);
  mysqli_stmt_bind_result($titleStmt, $cat_title);
  mysqli_stmt_store_result($titleStmt);
  mysqli_stmt_fetch($titleStmt);
  mysqli_stmt_close($titleStmt);




}
?>
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">
            <h1 class="page-header">
                <?php echo $cat_title;?>
            </h1>
             <small>Secondary Text</small>
            
            <?php  
           //if($stmt->num_rows==0){
            if(mysqli_stmt_num_rows($stmt) === 0){
                    echo "<h1 class='text-center'>Sorry, nothing relevant was found.</h1>";
                    }

                //while ($row = mysqli_fetch_assoc($stmt)) {
                while(mysqli_stmt_fetch($stmt)):
                  //display an excerpt by taking the content and only displaying a substring of the first 100 characters
            ?>
            <!-- Blog Post Structure -->
            <h2>
                <a href="post.php?p_id=<?php echo $post_id;?>"><?php echo $post_title; ?></a>
            </h2>
            <p class="lead">
                by <a href="about.php"> <?php echo $post_author; ?> </a>
            </p>
            <p><span class="glyphicon glyphicon-time"> Posted on <?php echo $post_date; ?></span></p>
            <hr>
            <a href="post.php?p_id=<?php echo $post_id;?>">
                <img class="img-responsive" src="images/<?php echo $post_image; ?>" alt="featured post image">
            </a>
            <hr>
            <p><?php echo substr($post_content,0,100); ?></p>
            <a class="btn btn-primary" href="post.php?p_id=<?php echo $post_id;?>">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

            <hr>
            <?php 
            endwhile;   //closes off the while loop querying all post information. The HTML code is now automatically replecated for each new post by being encased in this loop.
            mysqli_stmt_close($stmt);  ?>
            </div>
        
            <!-- Blog Sidebar Widgets Column -->
            <?php include "includes/sidebar.php"; ?>
          </div>
            <!-- /.row -->
 <hr>
<?php include "includes/footer.php"; ?>
</div>